import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppViewport from "./components/AppViewport";
import ErrorBoundary from "./components/ErrorBoundary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "カードゲーム制作",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // GameContextのProviderを追加
  // ...existing code...
  const GameProvider = require('./context/GameContext').GameProvider;
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <GameProvider>
          {/* 16:9 固定スケーリングのラッパー */}
          <div id="app-viewport-root">
            <AppViewport>
              <ErrorBoundary>
                {children}
              </ErrorBoundary>
            </AppViewport>
          </div>
        </GameProvider>
      </body>
    </html>
  );
}
